#!/bin/sh

echo "eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.137.2.9  netmask 255.255.255.255  broadcast 10.255.255.255
        inet6 fe80::216:3eff:fe5e:6c07  prefixlen 64  scopeid 0x20<link>
        ether 00:16:3e:5e:6c:07  txqueuelen 1000  (Ethernet)
        RX packets 74405  bytes 93418449 (89.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 54640  bytes 5365525 (5.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 47
"
